const fs = require('fs');
const jsdom = require('jsdom');
const { JSDOM } = jsdom;

// Generated by chatGPT, still need to verify this works

// Function to parse HTML and extract bookmarks
function extractBookmarks(html) {
  const dom = new JSDOM(html);
  const document = dom.window.document;
  const categories = document.querySelectorAll('DT > H3');
  let markdown = '';

  categories.forEach((category) => {
    const categoryName = category.textContent.trim();
    markdown += `## ${categoryName}\n`;

    const links = category.nextElementSibling.querySelectorAll('DT > A');
    links.forEach((link) => {
      const title = link.textContent.trim();
      const url = link.getAttribute('href').trim();
      markdown += `- [${title}](${url})\n`;
    });
    markdown += '\n'; // Add extra newline for readability
  });

  return markdown;
}

// Function to read HTML file, convert to Markdown, and write to file
function convertBookmarksToMarkdown(inputFilePath, outputFilePath) {
  fs.readFile(inputFilePath, { encoding: 'utf-8' }, (err, html) => {
    if (err) {
      console.error('Error reading the file:', err);
      return;
    }

    const markdown = extractBookmarks(html);

    fs.writeFile(outputFilePath, markdown, (err) => {
      if (err) {
        console.error('Error writing the markdown file:', err);
        return;
      }
      console.log(`Markdown has been saved to ${outputFilePath}`);
    });
  });
}

// Replace 'path/to/html/file.html' with the path to your HTML file
// and 'path/to/output/file.md' with the desired output Markdown file path
convertBookmarksToMarkdown('path/to/html/file.html', 'path/to/output/file.md');
